### ISSUE TITLE
Step 4 of ETH->SYS provides an explorer link that does not load

### ISSUE THREAD

**Issue by bstr156** [syscoin/sysethereum-dapp#12]
![image](https://user-images.githubusercontent.com/6069215/81583330-d4924080-9376-11ea-9337-832434ec520b.png)

txp.syscoin.org leads to this:
![image](https://user-images.githubusercontent.com/6069215/81583753-67cb7600-9377-11ea-9f36-8e81e2d2f579.png)

**Comment by sidhujag** [comment]
fixed in https://github.com/syscoin/sysethereum-dapp/commit/9a81cc32fe66c109d3195a0a315683208f889424
